baseURL = "https://neurodiverse.kristhecodingunicorn.com"
languageCode = "en-us"
paginate = 5
title = "Neurodiverse Kris"
mainSections = "post"

[params.sidebar]
  subtitle = "Blog about mental health and everyday life of a neurodiverse techie."
  emoji = "😺"
  avatar.src = "img/avatar.png"

[params.colorscheme]
  toggle = false
  default = "dark"

[params.footer]
  since = 2024

[menus]

[[menu.social]]
identifier = "email"
name = "Get in touch 💫"
url = "mailto:neurodiverse.kris@gmail.com"
  [menu.social.params]
  icon = "send"

[widgets]
[[widget.homepage]]
  type = "archives"
[[widget.homepage]]
  type = "search"

[[module.imports]]
path = "github.com/CaiJimmy/hugo-theme-stack/v3"